DART:
  KEY: ""
  MAPPER:
    1: 11013
    2: 11012
    3: 11014
    4: 11011
COLLECTOR:
  FILE:
    KR2ENG: "kr2eng.txt"
DATA:
  MARKET: data/corp_list.csv
ENV:
  SAVE_DIR: ""
EVAL:
  NON_CURRNET_ASSET_DISCOUNT: 0.8
