DART:
  KEY: b34dba1d3305ded5cf8022dab7ac5fe90c867e8b
  MAPPER:
    1: 11013
    2: 11012
    3: 11014
    4: 11011
DATA:
  MARKET: data/corp_list.csv
ENV:
  SAVE_DIR: C:\Users\HoHeon\OneDrive\Repositories\QuantizerKS\results
