DART:
  KEY: 125494f0d66cc9a1352fe47a74f8c78d4f2ed294
  MAPPER:
    1: 11013
    2: 11012
    3: 11014
    4: 11011
DATA:
  MARKET: data/corp_list.csv
ENV:
  SAVE_DIR: C:\Users\PC\Documents\repository\QuantizerKS\results
EVAL:
  NON_CURRNET_ASSET_DISCOUNT: 0.8
